### ISSUE TITLE
After state going off its cant trigger again after 5 sec

### ISSUE THREAD

**Issue by antonbek89** [wernerhp/appdaemon_aqara_motion_sensors#10]
Its still work ?

I facing with the issue

After state going off its cant trigger again after 5 sec

**Comment by Dengor1984** [comment]
The same...(

**Comment by caioclavico** [comment]
I have the same problem :/

**Comment by wernerhp** [comment]
Can you elaborate?  Do you use Aqara hub or a zigbee dongle with ZHA?  Did you do the hardware hack?
