### ISSUE TITLE
Aqara module name conflict with ControllerX

### ISSUE THREAD

**Issue by dimitripb** [wernerhp/appdaemon_aqara_motion_sensors#11]
When using ControllerX together with Appdaemon Aqara Motion Sensors there will be a module name conflict. ControllerX has also a module named 'aqara' and a file names aqara.py. Both apps won't work when you try to use them together. I solved this by renaming this module to aqara2. Then it works again. Maybe the source code should use a different name so this won't occur, like 'aqaramotion'.

**Comment by LintHart** [comment]
Just ran into this myself. Took me a couple of days to figure out until I realised ControllerX also plays with Aqara gear and they were probably cancelling each other out. Just to add, I also had to rename the file to be aqaramotion.py then update apps.yaml accordingly

**Comment by wernerhp** [comment]
Thanks for the workaround 👍
