### ISSUE TITLE
Problem Version 1.2.0

### ISSUE THREAD

**Issue by ninjax95** [wernerhp/appdaemon_aqara_motion_sensors#12]
The addon version 1.2.0 don't work not reset sensors to 5 second. : 
- AppDaemon 4 version: 0.7.1 
-  HASSIO : core-2021.12.0   supervisor-2021.12.1

It works with old version 1.0.1, do you know where the problem may be coming from ?

Thanks

**Comment by Hohenloherin** [comment]
I installed the app automatically in HACS and now I cannot find the file apps.yaml. Where is it located? 

If I just add the configuration of my sensors in config.yaml I get (of course) an error.

**Comment by wernerhp** [comment]
> I installed the app automatically in HACS and now I cannot find the file apps.yaml. Where is it located?
> 
> If I just add the configuration of my sensors in config.yaml I get (of course) an error.

Read the Configuration Guide
https://github.com/wernerhp/appdaemon_aqara_motion_sensors/issues/8#issue-784614244

**Comment by wernerhp** [comment]
> The addon version 1.2.0 don't work not reset sensors to 5 second. :
> 
>     * AppDaemon 4 version: 0.7.1
> 
>     * HASSIO : core-2021.12.0   supervisor-2021.12.1
> 
> 
> It works with old version 1.0.1, do you know where the problem may be coming from ?
> 
> Thanks

Which zigbee hub/integration do you use?

**Comment by Hohenloherin** [comment]
> I installed the app automatically in HACS and now ....

Thanks for your assistance wernerhp! I didn't install AppDaemon 4 properly. This was the solution to me: [https://github.com/wernerhp/appdaemon_aqara_motion_sensors/issues/8#issue-784614244](url)
