### ISSUE TITLE
not loading after installing from hacs

### ISSUE THREAD

**Issue by ishalem** [wernerhp/appdaemon_aqara_motion_sensors#2]
I get error:

Component error: aqara - Integration 'aqara' not found.

**Comment by wernerhp** [comment]
Thanks for reporting.  Could you provide some more information.
In which log do you find this?

What does your `app_daemon` the folder look like?
![image](https://user-images.githubusercontent.com/2578772/90955684-f9bb4280-e47f-11ea-9ccf-d34553340940.png)

Which version of HA, HACS and AppDaemon are you running?

A similar problem has been discussed [here](https://community.home-assistant.io/t/component-error-hacs-integration-hacs-not-found-and-component-error-sonoff-integration-sonoff-not-found/187946).

**Comment by ishalem** [comment]
I saw it in HA logs 
attached my structure
![image](https://user-images.githubusercontent.com/3824532/90974125-e74d1180-e530-11ea-92fe-05abd2b756c3.png)

**Comment by ishalem** [comment]
let me know if you need more info/logs

**Comment by wernerhp** [comment]
Can you confirm that the config for this `aqara` app is in `appdaemon/apps/apps.yaml` (not in `configuration.yaml`)

**Comment by ishalem** [comment]
looks like that was the issue, I don't see this error in the logs.
how can I tell its actually working?

**Comment by MicroSur** [comment]
Same question here. Sensors do not switch to off state after 5 seconds. Does this work only after the hardware hack?

//edit Sorry! My mistake in config, it works.

**Comment by wernerhp** [comment]
> looks like that was the issue, I don't see this error in the logs.
> how can I tell its actually working?

You can just look at any  of the configured sensors' state in Developer Tools.  When you move in front of the sensor it will turn on. 5 seconds later it will turn off.

Without the hardware hack, I think, it takes 60 seconds before it will turn on again.  
I can highly recommend the hardware hack.

**Comment by MrBigleg** [comment]
Is this now listed in HACS? I couldn't find it or are we to add a custom repository?

**Comment by ishalem** [comment]
its in hacs under automation section

**Comment by wernerhp** [comment]
@ishalem Were you able to test that it's working?  If so, please close the issue.

**Comment by MrBigleg** [comment]
> its in hacs under automation section

Strange, I can't see it and when I try to add a  custom repo I getthe following...

"Repository structure for v1.0.1 is not compliant"

HACS version 1.5.2

**Comment by ishalem** [comment]
after configuring in apps.yaml its working.
