### ISSUE TITLE
Hack aqara with ZHA integration

### ISSUE THREAD

**Issue by najjadasm** [wernerhp/appdaemon_aqara_motion_sensors#4]
Greetings,

I have aqara sensor with ZHA integration but appdaemon_aqara_motion_sensors not resat my sensor to 5 second.
I have config in app.yaml with appdaemon 4.

**Comment by oneseventhree** [comment]
also having this issue but with deconz

**Comment by rockzill** [comment]
the same issue here.. my motion sensors are connected with ZHA integration and their state isnt reset after 5 seconds even though I did hardware hack and also installed this app to appdaemon4

**Comment by punicawaikiki** [comment]
same here

**Comment by Fannangir** [comment]
Same here.
Is there any solution available for ZHA?

**Comment by wernerhp** [comment]
I don't have a dongle to test ZHA or DeConz with.
This app listens specifically for the Xiaomi Aqara integration's motion event
`self.listen_event(self.motion_sensor_state_on, "xiaomi_aqara.motion", entity_id=entity_id)`

If you provide more info on the ZHA and DeConz integration's event's I can add it.

**Comment by wernerhp** [comment]
You may find alternate solutions to ZHA or DeConz at https://community.home-assistant.io/t/aqara-motion-sensor-hack-for-5-sec/147959/30

**Comment by wernerhp** [comment]
Please try the latest release [v1.2.0](https://github.com/wernerhp/appdaemon_aqara_motion_sensors/releases/tag/v1.2.0) for ZHA

**Comment by s0ftice** [comment]
v1.2.0 works fine for me (HA core-2021.9.1 with ZHA).
This is top, thanks so much!

**Comment by wernerhp** [comment]
> Greetings,
> 
> I have aqara sensor with ZHA integration but appdaemon_aqara_motion_sensors not resat my sensor to 5 second. I have config in app.yaml with appdaemon 4.

Has the ZHA update fixed this for you?
