### ISSUE TITLE
Unable to use it on the latest HACS

### ISSUE THREAD

**Issue by abacao** [wernerhp/appdaemon_aqara_motion_sensors#5]
This is the message I'm getting when trying to install the repo manually.

```
Repostitory structure for v1.0.1 is not compliant
```

also I wasn't able to find this integration on the default HACS integrations.

**Comment by wernerhp** [comment]
Seems to work fine on HACS 1.6.0.  Need more info.  

Home Assistant > Configuration > Integrations > + > Search for 'HACS'> Install > HACS > Options > Enable AppDaemon apps > Submit

Home Assistant > HACS > Automation > + Search for 'wernerhp' > Aqara Motion Sensors > Install

**Comment by abacao** [comment]
I was trying to use a custom repository before.

I have enabled the AppDaemon4 from the default addon store in HACS, so the first part is done.

Now I'm trying the second part.
Inside HACS, I cannot find automations or your name.

Inside HACS I have the following options:
![Screenshot_20201010-104116_Home Assistant.jpg](https://user-images.githubusercontent.com/17479246/95651886-26d1bc00-0ae5-11eb-9d89-c7eac1276631.jpg)

Can you provide more guidance on please?

**Comment by wernerhp** [comment]
I have no idea what the **_deathly addon store_** is.  Could you provide more information?

It's available under the Automation section
![image](https://user-images.githubusercontent.com/2578772/95652124-2ccc9a80-0aef-11eb-8562-755a72a71460.png)

which you'll find once you enable the AppDaemon discovery
![image](https://user-images.githubusercontent.com/2578772/95652129-40780100-0aef-11eb-9acb-4cecbd37bc34.png)

under Home Assistant > Configuration > Integrations > HACS > Options
![image](https://user-images.githubusercontent.com/2578772/95652137-508fe080-0aef-11eb-8634-077d55925559.png)

**Comment by abacao** [comment]
Hello again,
It was "default", sorry for the auto-correct.
I was able to reach the "Aqara Motins Sensors" inside "automations" inside the "Home Assistant Community Store"
I was missing the tick on this image.
https://user-images.githubusercontent.com/2578772/95652129-40780100-0aef-11eb-9acb-4cecbd37bc34.png

I have opened a PR with instructions to make the instructions more clear.
Thanks
