### ISSUE TITLE
State not Changing

### ISSUE THREAD

**Issue by drowsell** [wernerhp/appdaemon_aqara_motion_sensors#7]
I'm currently using this addon to test the Aqara sensor before doing the hardware fix. Correct me if I'm wrong, but what the addon should do is change the state on the Binary Sensor from DETECTED to CLEAR after 5 seconds, correct? 

When I go into AppDaemon I see:

Name | State | Callbacks (instance) | Callbacks (AD Lifetime) | Arguments
aqara | idle | 0 | 0 | {"module":"aqara","class":"Aqara","timeo...

The state just stays idle. I'm wondering if this signifies that there is something currently wrong? 

My apps.yaml looks like this:

aqara:
  module: aqara
  class: Aqara
  timeout: 5
  motion_sensors:
    - binary_sensor.lumi_lumi_sensor_motion_aq2_7e554b05_ias_zone

**Comment by wernerhp** [comment]
No, the State in AppDaemon refers to the app's listener state.  The app is running and waiting for an event on the Entity, thus idle, so it should work just fine. If you watch closely it will flash a different state when motion is detected and the event is handled and then go back to idle.

Check out the state of your Entity in Home Assistant's Developer Tools or add it to a panel in Lovelace.  It should be Off, then turn On when it detects motion and switch back to Off after 5s.
