### ISSUE TITLE
Как настроить? \ How to configure it?

### ISSUE THREAD

**Issue by DivanX10** [wernerhp/appdaemon_aqara_motion_sensors#8]
К сожалению нет подробной инструкции как это настраивается и я не смог настроить. Пришлось спрашивать у знающих. Делюсь своим опытом, это может помочь вам. Сперва нужно убедиться, что у вас стоит аддон AppDaemon 4. Если не стоит, то ставим его.

![AppDaemon 4](https://user-images.githubusercontent.com/64090632/104371723-dda06680-5530-11eb-80c0-747b6e0fe776.JPG)

После установки аддона AppDaemon 4 должна появиться папка appdaemon.
![appdaemon01](https://user-images.githubusercontent.com/64090632/104372991-543d6400-5531-11eb-95cc-fe2da4443634.jpg)

Внутри этой папки должны быть подпапки, если этих подпапок нет, значит что-то пошло не так, тогда нужно сделать следующее:
1) Если стоит аддон AppDaemon 4, то удаляем этот аддон AppDaemon 4
2) Удаляем папку appdaemon
3) Перезагружаем Home Assistant
4) Ставим аддон AppDaemon 4 по новой
5) Должна появиться папка appdaemon и подпапки

Вот так должно быть в папке appdaemon
![appdaemon02](https://user-images.githubusercontent.com/64090632/104373024-60c1bc80-5531-11eb-9155-88a738d96fdb.JPG)

Далее заходим в папку apps и открываем файлик apps.yaml 
![apps](https://user-images.githubusercontent.com/64090632/104373708-d88fe700-5531-11eb-883c-19421e308805.jpg)

В этом файлике прописываем настройки для датчиков. Указываем время сброса статуса

Вот мой пример. Я решил разделить все датчики и не смешивать в одну кучу. Вы конечно можете смешать все в одну кучу как показал автор.
![konfig](https://user-images.githubusercontent.com/64090632/104377079-f57ae900-5536-11eb-8ce2-6b3d5714095e.JPG)

------------
Unfortunately, there is no detailed instructions on how to configure this and I was not able to configure it. I had to ask the knowledgeable ones. I share my experience, it can help you. First you need to make sure that you have the addon Ap Daemon 4. If not, then put it.

![AppDaemon 4](https://user-images.githubusercontent.com/64090632/104371723-dda06680-5530-11eb-80c0-747b6e0fe776.JPG)

After installing the Ap Daemon 4 addon, the app daemon folder should appear.

![appdaemon01](https://user-images.githubusercontent.com/64090632/104372991-543d6400-5531-11eb-95cc-fe2da4443634.jpg)

There should be subfolders inside this folder, if there are no subfolders, then something went wrong, then you need to do the following:
1) If there is an addon Ap Daemon 4, then remove this addon Ap Daemon 4
2) Deleting the app daemon folder
3) Restart the Home Assistant
4) We put the appdaemon 4 addon on a new one
5) The app daemon folder and subfolders should appear

This is how it should be in the app daemon folder
![appdaemon02](https://user-images.githubusercontent.com/64090632/104373024-60c1bc80-5531-11eb-9155-88a738d96fdb.JPG)

Next, go to the apps folder and open the app.yaml file
![apps](https://user-images.githubusercontent.com/64090632/104373708-d88fe700-5531-11eb-883c-19421e308805.jpg)

In this file, we specify the settings for the sensors. Specify the time to reset the status
Here is my example. I decided to separate all the sensors and not mix them in one pile. You can certainly mix everything into one pile as the author showed.
![konfig](https://user-images.githubusercontent.com/64090632/104377079-f57ae900-5536-11eb-8ce2-6b3d5714095e.JPG)

**Comment by karol-op** [comment]
thanks that helped me so much <3

**Comment by wernerhp** [comment]
Added to readme.

**Comment by labaland** [comment]
Is this still working? not working for me.
Appdeamon in docker compose, zigbee using Zigbee2mqtt

**Comment by wernerhp** [comment]
Yes, it works.  Share screenshots of your appdaemon config.

Did you do the hardware modification? 
What version of the Aqara sensor do you have?

**Comment by DivanX10** [comment]
> Yes, it works. Share screenshots of your appdaemon config.
> 
> Did you do the hardware modification? What version of the Aqara sensor do you have?

There is no need to use appdaemon to reset the status every 5 seconds. In order for this to work, the sensors themselves need to be switched to standby mode, when they record every 5 seconds instead of 60 seconds, after that there is a point in zigbee2mqtt where you can specify a time of 5 seconds and the status will be reset.


You need to connect these two lines, you can do it by soldering or drawing a path between them tightly with a pencil - graphene conducts current
![image](https://user-images.githubusercontent.com/64090632/233150126-9ea6dc4d-021f-4f92-be08-394db75705bc.png)


Then in the zigbee2mqtt settings, in the special settings section, specify 5 seconds
![image](https://user-images.githubusercontent.com/64090632/233150607-40c24a4d-3841-4810-8eaa-828c02cad0a2.png)
